// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.4
// source: pb/chat_room.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatClientMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnixMil int64    `protobuf:"varint,1,opt,name=unix_mil,json=unixMil,proto3" json:"unix_mil,omitempty"`
	ChatMsg *ChatMsg `protobuf:"bytes,2,opt,name=chat_msg,json=chatMsg,proto3" json:"chat_msg,omitempty"`
}

func (x *ChatClientMsg) Reset() {
	*x = ChatClientMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_room_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatClientMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatClientMsg) ProtoMessage() {}

func (x *ChatClientMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_room_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatClientMsg.ProtoReflect.Descriptor instead.
func (*ChatClientMsg) Descriptor() ([]byte, []int) {
	return file_pb_chat_room_proto_rawDescGZIP(), []int{0}
}

func (x *ChatClientMsg) GetUnixMil() int64 {
	if x != nil {
		return x.UnixMil
	}
	return 0
}

func (x *ChatClientMsg) GetChatMsg() *ChatMsg {
	if x != nil {
		return x.ChatMsg
	}
	return nil
}

type ChatServerMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnixMil  int64      `protobuf:"varint,1,opt,name=unix_mil,json=unixMil,proto3" json:"unix_mil,omitempty"`
	ChatMsgs []*ChatMsg `protobuf:"bytes,2,rep,name=chat_msgs,json=chatMsgs,proto3" json:"chat_msgs,omitempty"`
	Ok       bool       `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrMsg   *ErrorMsg  `protobuf:"bytes,4,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
}

func (x *ChatServerMsg) Reset() {
	*x = ChatServerMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_room_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatServerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatServerMsg) ProtoMessage() {}

func (x *ChatServerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_room_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatServerMsg.ProtoReflect.Descriptor instead.
func (*ChatServerMsg) Descriptor() ([]byte, []int) {
	return file_pb_chat_room_proto_rawDescGZIP(), []int{1}
}

func (x *ChatServerMsg) GetUnixMil() int64 {
	if x != nil {
		return x.UnixMil
	}
	return 0
}

func (x *ChatServerMsg) GetChatMsgs() []*ChatMsg {
	if x != nil {
		return x.ChatMsgs
	}
	return nil
}

func (x *ChatServerMsg) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ChatServerMsg) GetErrMsg() *ErrorMsg {
	if x != nil {
		return x.ErrMsg
	}
	return nil
}

type ChatMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ChatMsg) Reset() {
	*x = ChatMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_room_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMsg) ProtoMessage() {}

func (x *ChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_room_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMsg.ProtoReflect.Descriptor instead.
func (*ChatMsg) Descriptor() ([]byte, []int) {
	return file_pb_chat_room_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatMsg) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ErrorMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ErrorMsg) Reset() {
	*x = ErrorMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_chat_room_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMsg) ProtoMessage() {}

func (x *ErrorMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_room_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMsg.ProtoReflect.Descriptor instead.
func (*ErrorMsg) Descriptor() ([]byte, []int) {
	return file_pb_chat_room_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorMsg) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pb_chat_room_proto protoreflect.FileDescriptor

var file_pb_chat_room_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x69,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x78, 0x4d, 0x69, 0x6c,
	0x12, 0x23, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x07, 0x63, 0x68,
	0x61, 0x74, 0x4d, 0x73, 0x67, 0x22, 0x85, 0x01, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x6e, 0x69, 0x78, 0x5f,
	0x6d, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x78, 0x4d,
	0x69, 0x6c, 0x12, 0x25, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x52,
	0x08, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x22, 0x0a, 0x07, 0x65, 0x72, 0x72,
	0x5f, 0x6d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0x2f, 0x0a,
	0x07, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x1c,
	0x0a, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x3d, 0x0a, 0x0f,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x2a, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74, 0x12, 0x0e, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x1a, 0x0e, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x28, 0x01, 0x30, 0x01, 0x42, 0x04, 0x5a, 0x02, 0x2e,
	0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_chat_room_proto_rawDescOnce sync.Once
	file_pb_chat_room_proto_rawDescData = file_pb_chat_room_proto_rawDesc
)

func file_pb_chat_room_proto_rawDescGZIP() []byte {
	file_pb_chat_room_proto_rawDescOnce.Do(func() {
		file_pb_chat_room_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_chat_room_proto_rawDescData)
	})
	return file_pb_chat_room_proto_rawDescData
}

var file_pb_chat_room_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_chat_room_proto_goTypes = []interface{}{
	(*ChatClientMsg)(nil), // 0: ChatClientMsg
	(*ChatServerMsg)(nil), // 1: ChatServerMsg
	(*ChatMsg)(nil),       // 2: ChatMsg
	(*ErrorMsg)(nil),      // 3: ErrorMsg
}
var file_pb_chat_room_proto_depIdxs = []int32{
	2, // 0: ChatClientMsg.chat_msg:type_name -> ChatMsg
	2, // 1: ChatServerMsg.chat_msgs:type_name -> ChatMsg
	3, // 2: ChatServerMsg.err_msg:type_name -> ErrorMsg
	0, // 3: ChatRoomService.Chat:input_type -> ChatClientMsg
	1, // 4: ChatRoomService.Chat:output_type -> ChatServerMsg
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_chat_room_proto_init() }
func file_pb_chat_room_proto_init() {
	if File_pb_chat_room_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_chat_room_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatClientMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_room_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatServerMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_room_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_chat_room_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_chat_room_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_chat_room_proto_goTypes,
		DependencyIndexes: file_pb_chat_room_proto_depIdxs,
		MessageInfos:      file_pb_chat_room_proto_msgTypes,
	}.Build()
	File_pb_chat_room_proto = out.File
	file_pb_chat_room_proto_rawDesc = nil
	file_pb_chat_room_proto_goTypes = nil
	file_pb_chat_room_proto_depIdxs = nil
}
